### ISSUE TITLE
Encrypting the backup don't work ?

### ISSUE THREAD

**Issue by rican13** [salessandri/backup-to-dropbox#1]
Hello,
First of all thank you for this great project which serves me well.
However, I would like to use GPG encryption and it doesn't work.
Could you help me ?
PS: of course I installed all the prerequisites, but I am new to GPG.

1) --gpg-encrypt <KEY_FINGERPRINT> : What value can we put in this field?

2) command line executed :
backup-to-dropbox.py --gpg-encrypt "XXXXXXXXXX" --api-key "<Dropbox api token>" --backup-name "somefiles" --max-backups 4 "/home/user/somefiles"

2) results :
2021-03-23 12:42:11,670 - INFO - Performing cleanup of old backups
2021-03-23 12:42:11,670 - INFO - Request to files/list_folder
2021-03-23 12:42:12,161 - INFO - Encrypting file using GPG encryption to key: XXXXXXXXXX
2021-03-23 12:42:12,166 - WARNING - FAILURE status emitted from gpg process: option-parser 33554433
2021-03-23 12:42:12,167 - INFO - Writing encrypted output to file: /tmp/tmpjm3yb61j/encrypted-file
2021-03-23 12:42:12,167 - INFO - Encrypted output written successfully.
2021-03-23 12:42:12,167 - ERROR - Failed to encrypt backup file: option-parser 33554433
Traceback (most recent call last):
  File "/home/ricardo/.local/bin/backup-to-dropbox.py", line 58, in <module>
    main()
  File "/home/ricardo/.local/bin/backup-to-dropbox.py", line 51, in main
    backup_service.backup_paths(args.paths)
  File "/home/ricardo/.local/lib/python3.8/site-packages/backup_to_dropbox/services.py", line 24, in backup_paths
    backup_file = self.__encryption_service.encrypt(backup_file)
  File "/home/ricardo/.local/lib/python3.8/site-packages/backup_to_dropbox/services.py", line 87, in encrypt
    raise Exception(res.status)
Exception: option-parser 33554433

**Comment by salessandri** [comment]
Hi, there.

For the 1st question. The key fingerprint is the id of the public key you want to use to encrypt the file.
```
╰─➤  gpg --list-keys
<PATH TO KEYRING>
---------------------------------
pub   rsa4096 2016-11-11 [SC]
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
uid           [ unknown] Some Name <some@email.com>
sub   rsa4096 2016-11-11 [E]
```
The whole `XXX...XXX` string is the fingerprint.

You want to make sure that the default keyring for the user under which the the `backup-to-dropbox.py` is being executed has the key. If you run the command above on the host it should tell you which keyring file is being used and you can make `backup-to-dropbox.py` use that one specifically through command line options.

**Comment by rican13** [comment]
Hello,
Thank you for your reply.
I applied your recommendations but unfortunately it does not work.
Here is the data of my runtime environment.
I hope you can help me.
Cordially.
Ricardo

```
uname -a
Linux pcdev 5.8.0-45-generic #51~20.04.1-Ubuntu SMP Tue Feb 23 13:46:31 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

echo $USER
ricardo

python3 -V
Python 3.8.5

gpg --version
gpg (GnuPG) 2.2.19
libgcrypt 1.8.5
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Home: /home/ricardo/.gnupg
Algorithmes pris en charge :
Clef publique : RSA, ELG, DSA, ECDH, ECDSA, EDDSA
Chiffrement : IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256,
              TWOFISH, CAMELLIA128, CAMELLIA192, CAMELLIA256
Hachage : SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression : Non compressé, ZIP, ZLIB, BZIP2

gpg --list-keys
/home/ricardo/.gnupg/pubring.kbx
pub   rsa4096 2021-03-23 [SC]
      <----KEY_FINGERPRINT---->

. python module "backup-to-dropbox" directory
/home/ricardo/.local/bin/backup-to-dropbox.py
```

Command without GPG

```
backup-to-dropbox.py --api-key "<--- DROPBOX APP TOKEN --->" --backup-name "GDMP" --max-backups 4 "/home/ricardo/<--- SOME FILES --->"
```

Results without GPG = OK !

```
2021-03-24 10:45:19,342 - INFO - Creating Dropbox client
2021-03-24 10:45:19,342 - INFO - Performing cleanup of old backups
2021-03-24 10:45:19,343 - INFO - Request to files/list_folder
2021-03-24 10:45:19,964 - INFO - Uploading backup: <-some backup files->
2021-03-24 10:45:19,964 - INFO - Request to files/upload
2021-03-24 10:45:21,704 - INFO - Backup finished. Time elapsed: 2.36
```

Command with GPG

```
backup-to-dropbox.py --gpg-encrypt "<--- KEY_FINGERPRINT --->" --gpg-home "/home/ricardo/.gnupg" --gpg-pubkeyring "/home/ricardo/.gnupg/pubring.gpg" --api-key "<--- DROPBOX APP TOKEN --->" --backup-name "GDMP" --max-backups 4 "/home/ricardo/<--- SOME FILES --->"
```

Results with GPG = KO !

```
2021-03-24 11:12:13,782 - INFO - Creating Dropbox client
2021-03-24 11:12:13,810 - INFO - Log opened: Wed Mar 24 10:12:13 2021 UTC
2021-03-24 11:12:13,852 - INFO - Setting homedir to '/home/ricardo/.gnupg'
2021-03-24 11:12:13,864 - INFO - 
Initialised settings:
binary: /usr/bin/gpg
binary version: 2.2.19
homedir: /home/ricardo/.gnupg
ignore_homedir_permissions: False
keyring: /home/ricardo/.gnupg/pubring.gpg
secring: /home/ricardo/.gnupg/secring.gpg
default_preference_list: SHA512 SHA384 SHA256 AES256 CAMELLIA256 TWOFISH AES192 ZLIB ZIP Uncompressed
keyserver: hkp://wwwkeys.pgp.net
options: None
verbose: False
use_agent: False
2021-03-24 11:12:13,865 - INFO - Performing cleanup of old backups
2021-03-24 11:12:13,866 - INFO - Request to files/list_folder
2021-03-24 11:12:14,343 - INFO - Encrypting file using GPG encryption to key: <----KEY_FINGERPRINT---->
2021-03-24 11:12:14,357 - WARNING - FAILURE status emitted from gpg process: encrypt 9
2021-03-24 11:12:14,357 - INFO - Writing encrypted output to file: /tmp/tmpoqgo1bc2/encrypted-file
2021-03-24 11:12:14,357 - INFO - Encrypted output written successfully.
2021-03-24 11:12:14,357 - ERROR - Failed to encrypt backup file: encrypt 9
Traceback (most recent call last):
  File "/home/ricardo/.local/bin/backup-to-dropbox.py", line 58, in <module>
    main()
  File "/home/ricardo/.local/bin/backup-to-dropbox.py", line 51, in main
    backup_service.backup_paths(args.paths)
  File "/home/ricardo/.local/lib/python3.8/site-packages/backup_to_dropbox/services.py", line 24, in backup_paths
    backup_file = self.__encryption_service.encrypt(backup_file)
  File "/home/ricardo/.local/lib/python3.8/site-packages/backup_to_dropbox/services.py", line 87, in encrypt
    raise Exception(res.status)
Exception: encrypt 9
```

**Comment by salessandri** [comment]
I notice a few things:

1) The `--gpg-pubkeyring` parameter takes the filename only. You are using the whole path there.
2) In the output of `gpg --list-keys` it shows the keyring file as `/home/ricardo/.gnupg/pubring.kbx` but on the command you are using `pubring.gpg`

I suggest you try the command with `--gpg-pubkeyring pubring.kbx` and see how it goes

**Comment by rican13** [comment]
Yes, it actually works with your advice!
Thank you.
Cordially.
Ricardo
